name: job_finder
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks:
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.2.3
  build_runner: ^2.10.5
  google_fonts: ^6.3.3
  lottie: ^2.7.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.0
  dartz: ^0.10.1
  logger: ^2.6.2
  go_router: ^17.0.1
  equatable: ^2.0.8
  flutter_secure_storage: ^10.0.0
  fresh_dio: ^0.4.5
  dotted_line: ^3.2.3
  linkedin_login: ^3.2.3
  google_sign_in: ^7.2.0
  flutter_image_compress: ^2.4.0
  image_picker: ^1.2.1
  local_auth: ^2.3.0
  objectbox: ^5.1.0
  objectbox_flutter_libs: any
  share_plus: ^12.0.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  objectbox_generator: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.3

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/image/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/image/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/image/app_icon.png
